import Foundation

enum RecipeCatalog {
    static let mealTypes = ["Breakfast", "Lunch", "Dinner", "Snack", "Dessert"]
    static let dietaryOptions = ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free", "High-Protein"]

    static let all: [Recipe] = {
        let raw: [(String, String, String, Int, String, [String], [String], [String], String)] = [
            ("r01", "Garden Herb Omelette", "Fluffy eggs with fresh herbs and soft cheese.", 15, "Breakfast", ["Vegetarian", "High-Protein"], ["4 eggs", "2 tbsp milk", "Fresh herbs", "Salt", "Pepper", "Butter"], ["Whisk eggs with milk.", "Melt butter in a pan.", "Pour eggs and add herbs.", "Fold and serve warm."], "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600"),
            ("r02", "Berry Yogurt Bowl", "Creamy yogurt topped with seasonal berries and oats.", 8, "Breakfast", ["Vegetarian", "Gluten-Free"], ["Greek yogurt", "Mixed berries", "Oats", "Honey"], ["Add yogurt to a bowl.", "Top with berries and oats.", "Drizzle honey."], "https://images.unsplash.com/photo-1488477181946-6428d169c5a4?w=600"),
            ("r03", "Avocado Toast Stack", "Crispy toast with smashed avocado and chili flakes.", 10, "Breakfast", ["Vegetarian", "Vegan"], ["Sourdough", "1 avocado", "Lemon juice", "Chili flakes", "Salt"], ["Toast the bread.", "Mash avocado with lemon.", "Spread and season."], "https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=600"),
            ("r04", "Citrus Overnight Oats", "Make-ahead oats with orange zest and chia.", 5, "Breakfast", ["Vegetarian", "Vegan"], ["Rolled oats", "Almond milk", "Chia seeds", "Orange zest", "Maple syrup"], ["Mix all ingredients.", "Chill overnight.", "Stir before serving."], "https://images.unsplash.com/photo-1517673400267-0251440c45dc?w=600"),
            ("r05", "Spinach Feta Wrap", "Warm wrap filled with greens and feta.", 18, "Lunch", ["Vegetarian"], ["Tortilla", "Spinach", "Feta", "Tomato", "Olive oil"], ["Warm tortilla.", "Fill with spinach and feta.", "Drizzle oil and roll."], "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600"),
            ("r06", "Lemon Chickpea Salad", "Bright salad with chickpeas, cucumber, and lemon.", 20, "Lunch", ["Vegetarian", "Vegan", "Gluten-Free"], ["Chickpeas", "Cucumber", "Lemon", "Parsley", "Olive oil"], ["Rinse chickpeas.", "Chop vegetables.", "Toss with lemon dressing."], "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600"),
            ("r07", "Tomato Basil Soup", "Comforting soup finished with fresh basil.", 30, "Lunch", ["Vegetarian", "Vegan", "Dairy-Free"], ["Tomatoes", "Onion", "Garlic", "Basil", "Vegetable stock"], ["Sauté onion and garlic.", "Add tomatoes and stock.", "Simmer and blend.", "Finish with basil."], "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600"),
            ("r08", "Grilled Chicken Bowl", "Protein bowl with greens, grains, and herbs.", 35, "Lunch", ["High-Protein", "Dairy-Free"], ["Chicken breast", "Quinoa", "Mixed greens", "Lemon", "Olive oil"], ["Cook quinoa.", "Grill chicken.", "Assemble bowl and dress."], "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=600"),
            ("r09", "Sesame Noodle Cup", "Quick noodles with sesame and crisp vegetables.", 22, "Lunch", ["Vegetarian", "Dairy-Free"], ["Noodles", "Sesame oil", "Soy sauce", "Carrot", "Scallion"], ["Cook noodles.", "Toss with sauce.", "Top with vegetables."], "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600"),
            ("r10", "Roasted Veggie Tray", "Sheet-pan vegetables with garlic and thyme.", 40, "Dinner", ["Vegetarian", "Vegan", "Gluten-Free"], ["Zucchini", "Bell pepper", "Carrot", "Garlic", "Thyme", "Olive oil"], ["Chop vegetables.", "Toss with oil and herbs.", "Roast until tender."], "https://images.unsplash.com/photo-1511690658078-e261d127d013?w=600"),
            ("r11", "Herb Baked Salmon", "Oven salmon with lemon and dill.", 28, "Dinner", ["High-Protein", "Gluten-Free", "Dairy-Free"], ["Salmon fillet", "Lemon", "Dill", "Olive oil", "Salt"], ["Preheat oven.", "Season salmon.", "Bake until flaky."], "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=600"),
            ("r12", "Mushroom Risotto", "Creamy risotto with sautéed mushrooms.", 45, "Dinner", ["Vegetarian"], ["Arborio rice", "Mushrooms", "Onion", "Parmesan", "Stock"], ["Sauté onion and mushrooms.", "Toast rice.", "Add stock gradually.", "Finish with cheese."], "https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=600"),
            ("r13", "Turkey Chili Pot", "Hearty chili with beans and warm spices.", 50, "Dinner", ["High-Protein", "Dairy-Free"], ["Ground turkey", "Beans", "Tomato", "Chili powder", "Onion"], ["Brown turkey.", "Add spices and tomato.", "Simmer with beans."], "https://images.unsplash.com/photo-1455619455922-3e7b9d2e6c5a?w=600"),
            ("r14", "Garlic Shrimp Skillet", "Quick shrimp with garlic and parsley.", 18, "Dinner", ["High-Protein", "Gluten-Free", "Dairy-Free"], ["Shrimp", "Garlic", "Parsley", "Olive oil", "Lemon"], ["Sauté garlic.", "Cook shrimp quickly.", "Finish with lemon and parsley."], "https://images.unsplash.com/photo-1559737558-2f5a35f4523b?w=600"),
            ("r15", "Stuffed Bell Peppers", "Peppers filled with rice, herbs, and tomato.", 55, "Dinner", ["Vegetarian", "Gluten-Free"], ["Bell peppers", "Rice", "Tomato sauce", "Onion", "Cheese"], ["Parboil peppers.", "Mix filling.", "Stuff and bake."], "https://images.unsplash.com/photo-1604908177453-746295401a59?w=600"),
            ("r16", "Crispy Tofu Stir-Fry", "Golden tofu with colorful vegetables.", 25, "Dinner", ["Vegetarian", "Vegan", "Dairy-Free"], ["Firm tofu", "Broccoli", "Soy sauce", "Ginger", "Rice"], ["Press and cube tofu.", "Pan-fry until crisp.", "Stir-fry vegetables and toss."], "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600"),
            ("r17", "Honey Lime Chicken", "Pan chicken glazed with honey and lime.", 32, "Dinner", ["High-Protein", "Dairy-Free"], ["Chicken thighs", "Honey", "Lime", "Garlic", "Oil"], ["Sear chicken.", "Add glaze.", "Simmer until sticky."], "https://images.unsplash.com/photo-1598103442097-8b74394b95c6?w=600"),
            ("r18", "Veggie Pasta Primavera", "Light pasta with spring vegetables.", 30, "Dinner", ["Vegetarian"], ["Pasta", "Zucchini", "Peas", "Garlic", "Parmesan"], ["Boil pasta.", "Sauté vegetables.", "Toss together with cheese."], "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600"),
            ("r19", "Baked Sweet Potato", "Soft sweet potato with yogurt and herbs.", 45, "Dinner", ["Vegetarian", "Gluten-Free"], ["Sweet potatoes", "Greek yogurt", "Chives", "Olive oil", "Salt"], ["Bake potatoes.", "Split open.", "Top with yogurt and chives."], "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=600"),
            ("r20", "Coconut Curry Bowl", "Mild coconut curry with vegetables and rice.", 35, "Dinner", ["Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free"], ["Coconut milk", "Curry paste", "Vegetables", "Rice", "Lime"], ["Simmer curry paste in coconut milk.", "Add vegetables.", "Serve over rice."], "https://images.unsplash.com/photo-1455619455922-3e7b9d2e6c5a?w=600"),
            ("r21", "Apple Cinnamon Crisp", "Warm fruit dessert with oat topping.", 40, "Dessert", ["Vegetarian"], ["Apples", "Cinnamon", "Oats", "Butter", "Brown sugar"], ["Slice apples.", "Mix topping.", "Bake until golden."], "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?w=600"),
            ("r22", "Chocolate Mug Cake", "Single-serve cake ready in minutes.", 5, "Dessert", ["Vegetarian"], ["Flour", "Cocoa", "Sugar", "Milk", "Oil"], ["Mix dry ingredients.", "Add wet ingredients.", "Microwave until set."], "https://images.unsplash.com/photo-1578985545062-69921abac2d8?w=600"),
            ("r23", "Vanilla Chia Pudding", "Cool pudding with vanilla and fruit.", 10, "Dessert", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Chia seeds", "Plant milk", "Vanilla", "Fruit"], ["Stir chia into milk.", "Chill until thick.", "Top with fruit."], "https://images.unsplash.com/photo-1488477181946-6428d169c5a4?w=600"),
            ("r24", "Banana Oat Cookies", "Soft cookies with banana and oats.", 25, "Snack", ["Vegetarian", "Dairy-Free"], ["Bananas", "Oats", "Raisins", "Cinnamon"], ["Mash bananas.", "Mix with oats.", "Bake until firm."], "https://images.unsplash.com/photo-1499636136210-6f4ee915583e?w=600"),
            ("r25", "Hummus Veggie Cups", "Snack cups with hummus and crisp sticks.", 12, "Snack", ["Vegetarian", "Vegan", "Gluten-Free"], ["Hummus", "Carrot", "Cucumber", "Celery"], ["Portion hummus.", "Cut vegetables.", "Serve as dip cups."], "https://images.unsplash.com/photo-1505576399279-565b52d4ac71?w=600"),
            ("r26", "Trail Mix Packs", "Custom nut and fruit snack packs.", 8, "Snack", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Almonds", "Cashews", "Dried fruit", "Seeds"], ["Combine ingredients.", "Portion into bags.", "Store sealed."], "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=600"),
            ("r27", "Caprese Skewers", "Tomato, mozzarella, and basil bites.", 15, "Snack", ["Vegetarian", "Gluten-Free"], ["Cherry tomatoes", "Mozzarella", "Basil", "Balsamic"], ["Thread ingredients.", "Drizzle balsamic.", "Serve chilled."], "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=600"),
            ("r28", "Egg Fried Rice", "Fast skillet rice with eggs and peas.", 20, "Lunch", ["Vegetarian", "Dairy-Free"], ["Cooked rice", "Eggs", "Peas", "Soy sauce", "Scallion"], ["Scramble eggs.", "Add rice and peas.", "Season and toss."], "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=600"),
            ("r29", "Zucchini Noodles", "Light noodles with garlic and tomato.", 18, "Dinner", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Zucchini", "Garlic", "Cherry tomatoes", "Olive oil"], ["Spiralize zucchini.", "Sauté garlic and tomatoes.", "Toss noodles briefly."], "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=600"),
            ("r30", "Beef Stir Noodles", "Savory noodles with beef strips.", 28, "Dinner", ["High-Protein", "Dairy-Free"], ["Beef strips", "Noodles", "Broccoli", "Soy sauce", "Ginger"], ["Cook noodles.", "Sear beef.", "Stir-fry vegetables and combine."], "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=600"),
            ("r31", "Blueberry Pancakes", "Soft pancakes dotted with blueberries.", 25, "Breakfast", ["Vegetarian"], ["Flour", "Milk", "Egg", "Blueberries", "Baking powder"], ["Mix batter.", "Fold in berries.", "Cook on a hot pan."], "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=600"),
            ("r32", "Shakshuka Pan", "Eggs poached in spiced tomato sauce.", 30, "Breakfast", ["Vegetarian", "Gluten-Free", "High-Protein"], ["Eggs", "Tomatoes", "Onion", "Paprika", "Parsley"], ["Simmer sauce.", "Crack eggs in.", "Cover until set."], "https://images.unsplash.com/photo-1590412200988-a436970781fa?w=600"),
            ("r33", "Pesto Pasta Salad", "Cold pasta with pesto and greens.", 20, "Lunch", ["Vegetarian"], ["Pasta", "Pesto", "Cherry tomatoes", "Arugula"], ["Cook and cool pasta.", "Toss with pesto.", "Add tomatoes and greens."], "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=600"),
            ("r34", "Quinoa Tabbouleh", "Fresh herb salad with quinoa and lemon.", 22, "Lunch", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Quinoa", "Parsley", "Tomato", "Cucumber", "Lemon"], ["Cook quinoa.", "Chop herbs and vegetables.", "Dress with lemon."], "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=600"),
            ("r35", "Lentil Soup Pot", "Warming lentil soup with carrots.", 40, "Dinner", ["Vegetarian", "Vegan", "Dairy-Free", "Gluten-Free"], ["Lentils", "Carrot", "Onion", "Garlic", "Stock"], ["Sauté aromatics.", "Add lentils and stock.", "Simmer until soft."], "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600"),
            ("r36", "Chicken Caesar Salad", "Classic salad with crisp chicken.", 25, "Lunch", ["High-Protein"], ["Romaine", "Chicken", "Parmesan", "Croutons", "Dressing"], ["Grill chicken.", "Chop romaine.", "Toss and top."], "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=600"),
            ("r37", "Baked Cod Parcel", "Cod baked with lemon and herbs in foil.", 30, "Dinner", ["High-Protein", "Gluten-Free", "Dairy-Free"], ["Cod", "Lemon", "Herbs", "Olive oil", "Pepper"], ["Place fish on foil.", "Add lemon and herbs.", "Bake sealed."], "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=600"),
            ("r38", "Miso Broth Bowl", "Light broth with tofu and greens.", 20, "Dinner", ["Vegetarian", "Vegan", "Dairy-Free"], ["Miso paste", "Tofu", "Greens", "Scallion", "Stock"], ["Warm stock.", "Whisk in miso.", "Add tofu and greens."], "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600"),
            ("r39", "BBQ Veggie Skewers", "Grilled vegetable skewers with glaze.", 35, "Dinner", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Zucchini", "Mushroom", "Pepper", "Onion", "BBQ sauce"], ["Thread vegetables.", "Brush with sauce.", "Grill until charred."], "https://images.unsplash.com/photo-1555939596-19271bd1e3a8?w=600"),
            ("r40", "Creamy Tomato Pasta", "Silky tomato pasta ready for weeknights.", 25, "Dinner", ["Vegetarian"], ["Pasta", "Tomato sauce", "Cream", "Garlic", "Basil"], ["Cook pasta.", "Simmer sauce with cream.", "Combine and garnish."], "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600"),
            ("r41", "Greek Salad Plate", "Crisp salad with olives and feta.", 15, "Lunch", ["Vegetarian", "Gluten-Free"], ["Cucumber", "Tomato", "Olives", "Feta", "Oregano"], ["Chop vegetables.", "Add olives and feta.", "Dress lightly."], "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=600"),
            ("r42", "Peanut Butter Banana Toast", "Quick toast with peanut butter and banana.", 7, "Breakfast", ["Vegetarian", "Vegan"], ["Bread", "Peanut butter", "Banana", "Cinnamon"], ["Toast bread.", "Spread peanut butter.", "Top with banana."], "https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600"),
            ("r43", "Vegetable Frittata", "Oven frittata packed with vegetables.", 35, "Breakfast", ["Vegetarian", "Gluten-Free", "High-Protein"], ["Eggs", "Spinach", "Pepper", "Onion", "Cheese"], ["Sauté vegetables.", "Pour eggs.", "Bake until set."], "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600"),
            ("r44", "Mango Smoothie Cup", "Blended mango smoothie with yogurt.", 8, "Snack", ["Vegetarian", "Gluten-Free"], ["Mango", "Yogurt", "Honey", "Ice"], ["Blend all ingredients.", "Pour into a glass.", "Serve cold."], "https://images.unsplash.com/photo-1505252585461-04db1eb85825?w=600"),
            ("r45", "Rice Bean Burrito", "Hearty burrito with rice and beans.", 25, "Lunch", ["Vegetarian", "Vegan", "Dairy-Free"], ["Tortilla", "Rice", "Black beans", "Salsa", "Lettuce"], ["Warm tortilla.", "Fill with rice and beans.", "Add salsa and roll."], "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600"),
            ("r46", "Garlic Bread Bites", "Crispy garlic bread for sharing.", 15, "Snack", ["Vegetarian"], ["Baguette", "Butter", "Garlic", "Parsley"], ["Mix garlic butter.", "Spread on bread.", "Bake until crisp."], "https://images.unsplash.com/photo-1573140401552-3fab0b24306f?w=600"),
            ("r47", "Berry Compote Yogurt", "Warm berry topping over yogurt.", 12, "Dessert", ["Vegetarian", "Gluten-Free"], ["Mixed berries", "Sugar", "Lemon", "Yogurt"], ["Simmer berries.", "Cool slightly.", "Spoon over yogurt."], "https://images.unsplash.com/photo-1488477181946-6428d169c5a4?w=600"),
            ("r48", "Spiced Carrot Soup", "Smooth carrot soup with warm spice.", 35, "Lunch", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Carrots", "Onion", "Ginger", "Cumin", "Stock"], ["Cook vegetables.", "Blend smooth.", "Season to taste."], "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=600"),
            ("r49", "Herb Couscous Bowl", "Fluffy couscous with herbs and lemon.", 18, "Lunch", ["Vegetarian", "Vegan", "Dairy-Free"], ["Couscous", "Parsley", "Lemon", "Olive oil", "Cucumber"], ["Steam couscous.", "Fluff with fork.", "Fold in herbs and dressing."], "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=600"),
            ("r50", "Maple Roasted Carrots", "Sweet roasted carrots with maple glaze.", 30, "Dinner", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Carrots", "Maple syrup", "Olive oil", "Thyme", "Salt"], ["Toss carrots with glaze.", "Roast until caramelized.", "Serve hot."], "https://images.unsplash.com/photo-1447175008436-170170753886?w=600"),
            ("r51", "Tomato Bruschetta", "Toasted bread topped with fresh tomato.", 15, "Snack", ["Vegetarian", "Vegan", "Dairy-Free"], ["Baguette", "Tomato", "Basil", "Garlic", "Olive oil"], ["Toast bread.", "Mix tomato topping.", "Spoon onto toast."], "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600"),
            ("r52", "Coconut Rice Pudding", "Creamy rice pudding with coconut milk.", 40, "Dessert", ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"], ["Rice", "Coconut milk", "Sugar", "Vanilla"], ["Simmer rice in coconut milk.", "Sweeten and stir.", "Serve warm or chilled."], "https://images.unsplash.com/photo-1488477181946-6428d169c5a4?w=600")
        ]

        return raw.map {
            Recipe(
                id: $0.0,
                name: $0.1,
                summary: $0.2,
                cookTimeMinutes: $0.3,
                mealType: $0.4,
                dietaryTags: $0.5,
                ingredients: $0.6,
                steps: $0.7,
                imageURL: $0.8
            )
        }
    }()

    static func recipe(id: String) -> Recipe? {
        all.first { $0.id == id }
    }
}
